server:
  # 端口
  port: 8081
spring:
  redis:
    host: 120.76.57.148
    database: 0
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8  #最大连接数
        max-idle: 8    #最大空闲连接
        max-wait: -1   #最大等待时间,负数表示没有限制
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://公网ip:3306/yeb?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: 
    password: 
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）c
      connection-timeout: 30000
  # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  #rabbit配置
  rabbitmq:
    host: 120.76.57.148
    port: 5672
    username: 
    password: 
    virtual-host: /
    #消息失败回调
    publisher-returns: true
    #消息确认回调
    publisher-confirm-type: correlated



# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.xxxx.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.xxxx.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer
